### ISSUE TITLE
`count/time/installations`: error thrown on a particular filter

### ISSUE THREAD

**Issue by mindrones** [nestauk/asf_hp_market_tracker#260]
[This URL](https://staging--nesta-asf-hpmt.netlify.app/explorer/count/time/installations?categsGeoSortBy=total&categsStreamgraphsSorting=off&categsTimeGraph=streams&filters=(installerRegionNames:!(),installerRegionType:country21,propertyRegionNames:!(),propertyRegionType:country21,hp_feature_design:!(%27Another%20purpose%20only%27,%27DHW%20and%20another%20purpose%27,%27DHW%20only%27,%27Space%20Heat%20and%20another%20purpose%27,%27Space%20Heat,%20DHW%20and%20another%20purpose%27,%27Space%20heat%20and%20DHW%27,%27Space%20heat%20only%27,Unknown),installation_date:(gte:1672531200000,lte:1704067200000))&interval=1y&numTimeGraph=percentiles&regionType=itl21_1&regionTypes=!(country21,itl21_1,itl21_2,itl21_3,lad21)&stackedBarsExtents=absolute&stringsGeoSortBy=total&stringsStreamgraphsSorting=off&stringsTimeGraph=trends&stringsTopCount=20&trendType=progressive) is throwing the error:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '1')
    at Et (Trends.c8c9ce96.js:1:1337)
    at t.$$.update (Trends.c8c9ce96.js:1:15748)
    at $t (index.fa0fd956.js:1:7562)
    at rt (index.fa0fd956.js:1:7295)
```

**Comment by mindrones** [comment]
possible duplicate of #245
